name: 도커허브 downtimer 배포

on:
  push:
    branches:
      - mains

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 소스코드 체크아웃
        uses: actions/checkout@v3

      - name: 앱 빌드
        run: ./gradlew clean build -x test

      - name: 도커 이미지 빌드 및 푸시
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_REPO }}:1.0.0 .
          docker push ${{ secrets.DOCKER_REPO }}:1.0.0